ambicion/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
import environ


env = environ.Env()
environ.Env.read_env()

urlpatterns = [
    path(env('ADMIN_URL') + '/admin/', admin.site.urls),
    path('', include('client.urls')),
    path(env('MANAGER_URL') + '/manager/', include('manager.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/urls.py
from django.urls import path
from . import views

app_name = 'client'

urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('line-webhook/dev/', views.LineWebhookDevView.as_view(), name='line_webhook_dev'),
    path('line-webhook/alpha/', views.LineWebhookAlphaView.as_view(), name='line_webhook_alpha'),
    path('line-webhook/beta/', views.LineWebhookBetaView.as_view(), name='line_webhook_beta'),
]

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'

urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('main_slide/', views.MainSlideView.as_view(), name='main_slide'),
    path('sample/', views.SampleView.as_view(), name='sample'),
    path('family/', views.FamilyView.as_view(), name='family'),
    path('delete/<str:page_name>/<int:pk>/', views.DeleteView.as_view(), name='delete'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

manager/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager


class UserManager(BaseUserManager):
  use_in_migrations = True

  def _create_user(self, username, email, password, **extra_fields):
    if not username:
      raise ValueError('The given username must be set')
    email = self.normalize_email(email)
    username = self.model.normalize_username(username)
    user = self.model(username=username, email=email, **extra_fields)
    user.set_password(password)
    user.save(using=self.db)
    return user

  def create_user(self, username, email=None, password=None, **extra_fields):
    extra_fields.setdefault('is_staff', False)
    extra_fields.setdefault('is_superuser', False)
    return self._create_user(username, password, **extra_fields)

  def create_superuser(self, username, email, password, **extra_fields):
    extra_fields.setdefault('is_staff', True)
    extra_fields.setdefault('is_superuser', True)
    if extra_fields.get('is_staff') is not True:
      raise ValueError('Superuser must have is_staff=True')
    if extra_fields.get('is_superuser') is not True:
      raise ValueError('Superuser must have is_superuser=True')
    return self._create_user(username, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
  email = models.EmailField('メールアドレス', max_length=255, unique=True)
  username = models.CharField('ユーザーネーム', max_length=255)
  last_name = models.CharField('苗字', max_length=255)
  first_name = models.CharField('名前', max_length=255)
  password = models.CharField('パスワード', max_length=128)
  is_active = models.BooleanField(default=True)
  is_staff = models.BooleanField(default=False)

  objects = UserManager()
  
  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['username']

  class Meta:
    db_table = 'users'
        
    def __str__(self):
      return f'{self.first_name} {self.last_name}'

manager/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from client.models import Gallery, Sample, Family


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    pass


class GalleryForm(forms.ModelForm):
  class Meta:
    model = Gallery
    fields = ['img', 'title']


class SampleForm(forms.ModelForm):
  class Meta:
    model = Sample
    fields = ['img', 'name']
       

manager/views.py
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView, View
from client.models import Gallery, Sample, Family
from .forms import GalleryForm, SampleForm, LoginForm
from django.contrib import messages
from .gd_client import GoogleDriveClient, DeleteFailedError


class Login(LoginView):
    template_name = 'manager/login.html'
    from_class = LoginForm


class Logout(LogoutView):
    template_name = 'manager/login.html'


class TopView(LoginRequiredMixin, TemplateView):
    template_name = 'manager/top.html'


class MainSlideView(LoginRequiredMixin, CreateView):
    template_name = 'manager/main_slide.html'
    form_class = GalleryForm

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gallery_list'] = Gallery.objects.all()
        context['gallery_count'] = Gallery.objects.count()
        return context

    def post(self, request, *args, **kwargs):
        target_pk = request.POST.get('pk')
        target_img = request.FILES.get('img')
        target_title = request.POST.get('title')
        before_img_name = Gallery.objects.get(pk=target_pk).img.name
        is_update_img = False
        if target_img is None:
            target_img = Gallery.objects.get(pk=target_pk).img
        else:
            is_update_img = True
        if target_title == '':
            target_title = Gallery.objects.get(pk=target_pk).title
        try:
            Gallery.objects.update_or_create(
                pk=target_pk,
                defaults={
                    'img': target_img,
                    'title': target_title,
                    'is_standby': False,
                },
            )
            if is_update_img:
                gdc = GoogleDriveClient()
                gdc.upload_file(Gallery.objects.get(pk=target_pk).img.url, 'gallery')
                if len(before_img_name) > 2:
                    print(before_img_name)
                    gdc.delete_file(before_img_name, 'gallery')
            messages.success(request, '更新完了！')
        except DeleteFailedError:
            messages.error(request, 'googleドライブのファイル削除に失敗！不要なファイルを削除してください。')
        except Exception:
            import traceback

            traceback.print_exc()
            messages.error(request, '同じタイトルは使えない！')
        return redirect('manager:main_slide')


class SampleView(CreateView, LoginRequiredMixin):
    template_name = 'manager/sample.html'
    form_class = SampleForm

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sample_list'] = Sample.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        target_pk = request.POST.get('pk')
        target_img = request.FILES.get('img')
        target_name = request.POST.get('name')
        before_img_name = Sample.objects.get(pk=target_pk).img.name
        is_update_img = False
        if target_img is None:
            target_img = Sample.objects.get(pk=target_pk).img
        else:
            is_update_img = True
        if target_name == '':
            target_name = Sample.objects.get(pk=target_pk).name
        try:
            Sample.objects.update_or_create(
                id=target_pk,
                defaults={'img': target_img, 'name': target_name, 'is_standby': False},
            )
            if is_update_img:
                gdc = GoogleDriveClient()
                num_check_is_exist_file_name = 2
                gdc.upload_file(Sample.objects.get(pk=target_pk).img.url, 'sample')
                if len(before_img_name) > num_check_is_exist_file_name:
                    gdc.delete_file(before_img_name, 'sample')
            messages.success(request, '更新完了！')
        except DeleteFailedError:
            messages.error(request, 'googleドライブのファイル削除に失敗！不要なファイルを削除してください。')
        except Exception:
            import traceback

            traceback.print_exc()
            messages.error(request, '同じ名前は使えない！')
        return redirect('manager:sample')


class FamilyView(CreateView, LoginRequiredMixin):
    template_name = 'manager/family.html'
    model = Family


class DeleteView(View, LoginRequiredMixin):
    def get(self, request, *args, **kwargs):
        page_name = self.kwargs['page_name']
        target_pk = self.kwargs['pk']
        if page_name == 'main_slide':
            Gallery.objects.update_or_create(
                pk=target_pk, defaults={'is_standby': True}
            )
        elif page_name == 'sample':
            Sample.objects.update_or_create(pk=target_pk, defaults={'is_standby': True})
        elif page_name == 'family':
            Family.objects.update_or_create(pk=target_pk, defaults={'is_standby': True})
        return redirect(f'manager:{page_name}')

manager/templates/manager/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AMBICIÓN MANAGER</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'ambicion/favicon.ico' %}" />
    <!-- Bootstrap 5.0 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'manager/css/styles.css' %}" />
    <!--  Font Awesome-->
    <script
      src="https://kit.fontawesome.com/fea1fb9366.js"
      crossorigin="anonymous"
    ></script>

    <!-- jQuery -->
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light p-3">
      <img
        class="navbar-logo"
        src="{% static 'client/images/design_pieces/logo_black.png' %}"
        alt=""
      />
      <div
        class="d-flex col-12 col-md-3 col-lg-2 mb-2 mb-lg-0 flex-wrap flex-md-nowrap justify-content-between"
      >
        <button
          class="navbar-toggler d-md-none collapsed mb-3"
          type="button"
          data-toggle="collapse"
          data-target="#sidebar"
          aria-controls="sidebar"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div
        class="col-12 col-md-5 col-lg-8 d-flex align-items-center justify-content-md-end mt-3 mt-md-0"
      >
        <div class="mr-3 mt-1"></div>
        <div class="dropdown">
          <button
            class="account-btn btn btn-light dropdown-toggle"
            type="button"
            id="dropdownMenuButton"
            data-toggle="dropdown"
            aria-expanded="false"
          >
            Hello, {{ user.first_name }} {{ user.last_name }}
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li>
              <a class="dropdown-item" href="{% url 'manager:logout' %}"
                >Sign out</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <nav
          id="sidebar"
          class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"
        >
          {% include 'manager/sidebar.html' %}
        </nav>
        <div class="col-md-3 col-lg-2"></div>
        <main class="contents-area col-md-9 col-lg-10">
          {% block contents %}{% endblock %}
        </main>
      </div>
    </div>

    <!-- insert scripts here -->
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
      integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

manager/templates/manager/login.html
{% load static %} {% load widget_tweaks %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AMBICIÓN MANAGER</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'ambicion/favicon.ico' %}" />
    <!-- Bootstrap 5.0 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'manager/css/login_styles.css' %}" />
    <!--  Font Awesome-->
    <script
      src="https://kit.fontawesome.com/fea1fb9366.js"
      crossorigin="anonymous"
    ></script>
    <!-- jQuery -->
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <img
      src="{% static 'client/images/design_pieces/logo_white.png' %}"
      alt=""
      class="logo"
    />
    <div class="form-container">
      <form action="{% url 'manager:login' %}" method="post">
        {% csrf_token %}
        <input
          type="text"
          name="username"
          placeholder="Your Email"
          class="form-item form-control center-block"
        />
        <input
          type="password"
          name="password"
          placeholder="Password"
          class="form-item form-control center-block"
        />
        <p>
          <input type="hidden" name="next" value="{% url 'manager:top' %}" />
        </p>
        <p>
          <input type="submit" value="Login" class="form-btn btn btn-dark" />
        </p>
      </form>
    </div>
  </body>
</html>

manager/templates/manager/main_slide.html
{% extends 'manager/base.html' %} {% load static %} {% load widget_tweaks %}
{% block contents %}
<div class="main-slide-contents">
  {% for message in messages %}
  <div {% if message.tags %}class="{{ message.tags }}" {% endif %}>
    {{ message }}
  </div>
  {% endfor %}
  <h1 class="contents-title">Main Slide</h1>
  <div
    id="carouselExampleIndicators"
    class="carousel slide"
    data-bs-ride="carousel"
    data-bs-interval="false"
  >
    <div class="carousel-indicators">
      {% for gallery in gallery_list %} {% if forloop.counter == 1 %}
      <button
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide-to="{{ forloop.counter|add:'-1' }}"
        class="active"
        aria-current="true"
        aria-label="Slide {{ forloop.counter }}"
      ></button>
      {% else %}
      <button
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide-to="{{ forloop.counter|add:'-1' }}"
        aria-label="Slide {{ forloop.counter }}"
      ></button>
      {% endif %} {% endfor %}
    </div>
    <div class="carousel-inner">
      {% for gallery in gallery_list %} {% if forloop.counter == 1 %}
      <div class="carousel-item active">
        {% if gallery.is_standby %}
        <form
          method="post"
          enctype="multipart/form-data"
          id="add-new-form-{{ forloop.counter }}"
        >
          {% csrf_token %}
          <label
            for="gallery-img-{{ forloop.counter }}-input"
            class="gallery-img-label"
          >
            <img
              class="hover-item gallery-img"
              src="{% static 'manager/images/main_slide_standby.png' %}"
              id="gallery-img-{{ forloop.counter }}"
            />
          </label>
          <input
            type="file"
            class="gallery-img-input form-control"
            id="gallery-img-{{ forloop.counter }}-input"
            name="img"
            accept="image/*"
            hidden
          />
          <h2 class="gallery-title">New</h2>
          <input
            type="text"
            class="gallery-title-input form-control hover-item"
            name="title"
            id="gallery-title-{{ forloop.counter }}-input"
          />
          <input type="hidden" name="pk" value="{{ gallery.pk }}" />
          <button
            type="button"
            class="gallery-add-btn btn btn-primary"
            id="gallery-add-btn-{{ forloop.counter }}"
          >
            Add
          </button>
        </form>
        {% else %}
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <label
            for="gallery-img-{{ forloop.counter }}-input"
            class="gallery-img-label"
          >
            <img
              class="hover-item gallery-img"
              src="{{ gallery.img.url }}"
              id="gallery-img-{{ forloop.counter }}"
            />
          </label>
          <input
            type="file"
            class="gallery-img-input form-control"
            id="gallery-img-{{ forloop.counter }}-input"
            name="img"
            accept="image/*"
            hidden
          />
          <h2 class="gallery-title">{{ gallery.title }}</h2>
          <input
            type="text"
            class="gallery-title-input form-control hover-item"
            name="title"
            value="{{ gallery.title }}"
          />
          <input type="hidden" name="pk" value="{{ gallery.pk }}" />
          <button
            onClick="submit();"
            type="button"
            class="gallery-update-btn btn btn-success"
          >
            Update
          </button>
          <a
            href="{% url 'manager:delete' 'main_slide' gallery.pk  %}"
            onclick="return confirm('削除する？');"
            class="gallery-update-btn btn btn-danger"
            >Delete</a
          >
        </form>
        {% endif %}
      </div>
      {% else %}
      <div class="carousel-item">
        {% if gallery.is_standby %}
        <form
          method="post"
          enctype="multipart/form-data"
          id="add-new-form-{{ forloop.counter }}"
        >
          {% csrf_token %}
          <label
            for="gallery-img-{{ forloop.counter }}-input"
            class="gallery-img-label"
          >
            <img
              class="hover-item gallery-img"
              src="{% static 'manager/images/main_slide_standby.png' %}"
              id="gallery-img-{{ forloop.counter }}"
            />
          </label>
          <input
            type="file"
            class="gallery-img-input form-control"
            id="gallery-img-{{ forloop.counter }}-input"
            name="img"
            accept="image/*"
            hidden
          />
          <h2 class="gallery-title">New</h2>
          <input
            type="text"
            class="gallery-title-input form-control hover-item"
            name="title"
            id="gallery-title-{{ forloop.counter }}-input"
          />
          <input type="hidden" name="pk" value="{{ gallery.pk }}" />
          <button
            type="button"
            class="gallery-add-btn btn btn-primary"
            id="gallery-add-btn-{{ forloop.counter }}"
          >
            Add
          </button>
        </form>
        {% else %}
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <label
            for="gallery-img-{{ forloop.counter }}-input"
            class="gallery-img-label"
          >
            <img
              class="hover-item gallery-img"
              src="{{ gallery.img.url }}"
              id="gallery-img-{{ forloop.counter }}"
            />
          </label>
          <input
            type="file"
            class="gallery-img-input form-control"
            id="gallery-img-{{ forloop.counter }}-input"
            name="img"
            accept="image/*"
            hidden
          />
          <h2 class="gallery-title">{{ gallery.title }}</h2>
          <input
            type="text"
            class="gallery-title-input form-control hover-item"
            name="title"
            value="{{ gallery.title }}"
          />
          <input type="hidden" name="pk" value="{{ gallery.pk }}" />
          <button
            onClick="submit();"
            type="button"
            class="gallery-update-btn btn btn-success"
          >
            Update
          </button>
          <a
            href="{% url 'manager:delete' 'main_slide' gallery.pk  %}"
            onclick="return confirm('削除する？');"
            class="gallery-update-btn btn btn-danger"
            >Delete</a
          >
        </form>
        {% endif %}
      </div>
      {% endif %} {% endfor %}
    </div>
    <button
      class="carousel-control-prev"
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button
      class="carousel-control-next"
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
<script>
  $(function () {
    $(".gallery-img-input").on("change", function () {
      const input_id = $(this).prop("id");
      const img_id = "#" + input_id.replace("-input", "");
      const file = $(this).prop("files")[0];
      let reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = function () {
        $(img_id).attr("src", reader.result);
      };
    });

    $(document).ready(function () {
      $(window).keydown(function (event) {
        if (event.keyCode == 13) {
          event.preventDefault();
          return false;
        }
      });
    });

    $(".gallery-add-btn").on("click", function () {
      const input_id = $(this).prop("id");
      const img_input_id = "#" + input_id.replace("add-btn", "img") + "-input";
      const title_input_id =
        "#" + input_id.replace("add-btn", "title") + "-input";
      const form_id = "#" + input_id.replace("gallery-add-btn", "add-new-form");
      if ($(img_input_id).val() === "") {
        alert("画像を選択して！");
        $(this).focus();
        return false;
      } else if ($(title_input_id).val() === "") {
        alert("タイトルを入力して！");
        return false;
      }
      $(form_id).submit();
    });
  });
</script>
{% endblock %}

manager/templates/manager/sample.html
{% extends 'manager/base.html' %} {% load static %}
{% block contents %}
{% for message in messages %}
<div {% if message.tags %}class="{{ message.tags }}" {% endif %}>
  {{ message }}
</div>
{% endfor %}
<h1 class="contents-title">Sample</h1>
<div class="sample-contents row">
  {% for sample in sample_list %}
  <div class="col-4">
    {% if sample.is_standby %}
    <form
      method="post"
      enctype="multipart/form-data"
      id="add-new-form-{{ forloop.counter }}"
    >
      {% csrf_token %}
      <label for="sample-img-{{ forloop.counter }}-input">
        <div class="sample-add-img-frame">
          <img
            class="hover-item sample-img"
            src="{% static 'manager/images/logo_black.png' %}"
            aslign="bottom"
            id="sample-img-{{ forloop.counter }}"
          />
        </div>
      </label>
      <input
        type="file"
        class="sample-img-input form-control"
        id="sample-img-{{ forloop.counter }}-input"
        name="img"
        accept="image/*"
        hidden
      />
      <input type="hidden" name="pk" value="{{ sample.pk }}" />
      <input
        type="text"
        class="sample-name-input form-control"
        name="name"
        id="sample-name-{{ forloop.counter }}-input"
      />
      <button
        type="button"
        class="sample-add-btn btn btn-primary"
        id="sample-add-btn-{{ forloop.counter }}"
      >
        Add
      </button>
    </form>
    {% else %}
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <label for="sample-img-{{ forloop.counter }}-input">
        <img
          class="hover-item sample-img"
          src="{{ sample.img.url }}"
          aslign="bottom"
          id="sample-img-{{ forloop.counter }}"
        />
      </label>
      <input
        type="file"
        class="sample-img-input form-control"
        id="sample-img-{{ forloop.counter }}-input"
        name="img"
        accept="image/*"
        hidden
      />
      <input type="hidden" name="pk" value="{{ sample.pk }}" />
      <input
        type="text"
        class="sample-name-input form-control"
        value="{{ sample.name }}"
        name="name"
      />
      <button
        onClick="submit();"
        type="button"
        class="sample-update-btn btn btn-success"
      >
        Update
      </button>
      <a
        href="{% url 'manager:delete' 'sample' sample.pk  %}"
        onclick="return confirm('削除する？');"
        class="sample-update-btn btn btn-danger"
        >Delete</a
      >
    </form>
    {% endif %}
  </div>
  {% endfor %}
</div>
<script>
  $(function () {
    $(".sample-img-input").on("change", function () {
      const input_id = $(this).prop("id");
      const img_id = "#" + input_id.replace("-input", "");
      const file = $(this).prop("files")[0];
      let reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = function () {
        $(img_id).attr("src", reader.result);
      };
    });

    $(document).ready(function () {
      $(window).keydown(function (event) {
        if (event.keyCode == 13) {
          event.preventDefault();
          return false;
        }
      });
    });

    $(".sample-add-btn").on("click", function () {
      const input_id = $(this).prop("id");
      const img_input_id = "#" + input_id.replace("add-btn", "img") + "-input";
      const name_input_id =
        "#" + input_id.replace("add-btn", "name") + "-input";
      const form_id = "#" + input_id.replace("sample-add-btn", "add-new-form");
      if ($(img_input_id).val() === "") {
        alert("画像を選択して！");
        $(this).focus();
        return false;
      } else if ($(name_input_id).val() === "") {
        alert("名前を入力して！");
        return false;
      }
      $(form_id).submit();
    });
  });
</script>
{% endblock %}

manager/templates/manager/sidebar.html
<div class="position-sticky pt-md-5">
  <ul class="nav flex-column">
    <li class="nav-item">
      <a class="nav-link sidebar-item" href="{% url 'manager:top' %}">
        <i class="sidebar-logo fa-solid fa-chart-line"></i>Dashboard
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link sidebar-item" href="{% url 'manager:main_slide' %}">
        <i class="sidebar-logo fa-solid fa-tv"></i>Main Slide
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link sidebar-item" href="{% url 'manager:sample' %}">
        <i class="sidebar-logo fa-regular fa-pen-to-square"></i>Sample
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link sidebar-item" href="#">
        <i class="sidebar-logo fa-solid fa-users-rectangle"></i>Family
      </a>
    </li>
  </ul>
</div>

manager/templates/manager/top.html
{% extends 'manager/base.html' %} {% load static %} {% block contents %}
<h1 class="contents-title">Dashboard</h1>

<div class="qr-code-container">
  <div class="qr-code-wrapper">
    <h2>開発者向けLINE公式アカウント</h2>
    <img src="https://qr-official.line.me/gs/M_717uaptm_GW.png?oat_content=qr" alt="LINE公式アカウント QRコード" class="qr-code-image">
    <p class="qr-code-text">上記QRコードからLINE公式アカウントに友達追加してください。</p>
  </div>
</div>

<style>
  .qr-code-container {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 40px 20px;
  }

  .qr-code-wrapper {
    text-align: center;
    background: #f5f5f5;
    padding: 30px;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  }

  .qr-code-wrapper h2 {
    margin: 0 0 20px 0;
    font-size: 18px;
    color: #333;
  }

  .qr-code-image {
    width: 250px;
    height: 250px;
    border: 2px solid #ddd;
    padding: 10px;
    background: white;
    border-radius: 4px;
  }

  .qr-code-text {
    margin: 20px 0 0 0;
    font-size: 14px;
    color: #666;
  }
</style>

{% endblock %}