ambicion/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
import environ


env = environ.Env()
environ.Env.read_env()

urlpatterns = [
    path(env('ADMIN_URL') + '/admin/', admin.site.urls),
    path('', include('client.urls')),
    path(env('MANAGER_URL') + '/manager/', include('manager.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/urls.py
from django.urls import path
from . import views

app_name = 'client'

urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('line-webhook/dev/', views.LineWebhookDevView.as_view(), name='line_webhook_dev'),
    path('line-webhook/alpha/', views.LineWebhookAlphaView.as_view(), name='line_webhook_alpha'),
    path('line-webhook/beta/', views.LineWebhookBetaView.as_view(), name='line_webhook_beta'),
]

client/models.py
from django.db import models


class Gallery(models.Model):  # トップページのメインスライド
    img = models.ImageField(upload_to='gallery/', blank=True, null=True)
    title = models.CharField(max_length=100, unique=True, null=True, blank=True)
    is_standby = models.BooleanField(default=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        if self.is_standby:
            return f'[{self.pk}] is on standby.'
        return f'[{self.pk}]{self.title} PATH:{self.img.url}'


class Sample(models.Model):  # デザインデータサンプル画像
    img = models.ImageField(upload_to='sample/', null=True, blank=True)
    name = models.CharField(max_length=15, unique=True, null=True, blank=True)
    is_standby = models.BooleanField(default=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        if self.is_standby:
            return f'[{self.pk}] is on standby.'
        return f'[{self.pk}]{self.name} PATH:{self.img.url}'


class Family(models.Model):  # ファミリー
    img = models.ImageField(upload_to='family/', null=True, blank=True)
    title = models.CharField(max_length=100, null=True, blank=True)
    text = models.TextField(max_length=300, null=True, blank=True)
    is_standby = models.BooleanField(default=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        if self.is_standby:
            return f'[{self.pk}]is on standby.'
        return f'[{self.pk}]{self.title}: {self.img.url}'


class LineUser(models.Model):
    account = models.CharField(max_length=50, default='dev')
    user_id = models.CharField(max_length=50)
    name = models.CharField(max_length=100)
    is_receiver = models.BooleanField(default=False)

    class Meta:
        ordering = ['pk']
        unique_together = [['account', 'user_id'], ['account', 'name']]

    def __str__(self):
        return f'Line User ID: {self.user_id}'

client/views.py
from datetime import datetime
import json
from django.http import HttpResponse
import environ
import requests

from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.core.mail import send_mail

from client.services.line_api_service import LINE_API_Service, MessageConsumptionLimitError

from .models import Gallery, Sample, Family
from .services.instagram_api_service import InstagramAPIService

# Set Environment Variables
env = environ.Env()
environ.Env.read_env()


PYTHON_EMAIL = env('PYTHON_EMAIL')
AMBICION_EMAIL = env('AMBICION_EMAIL')
SECRET_KEY = env('SECRET_KEY')
TURNSTILE_SITEKEY = env('TURNSTILE_SITEKEY')
TURNSTILE_SECRET_KEY = env('TURNSTILE_SECRET_KEY')
BLOCK_LIST = env('BLOCK_LIST')


def validate_turnstile(token, secret, remoteip=None):
    url = 'https://challenges.cloudflare.com/turnstile/v0/siteverify'

    data = {
        'secret': secret,
        'response': token
    }

    if remoteip:
        data['remoteip'] = remoteip

    try:
        response = requests.post(url, data=data, timeout=10)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as e:
        print(f"Turnstile validation error: {e}")
        return {'success': False, 'error-codes': ['internal-error']}


class TopView(TemplateView):
    template_name = 'client/index.html'
  
    def get_context_data(self, **kwargs):
        current_year = datetime.now().year
        context = super().get_context_data(**kwargs)
        context['year'] = current_year
        context['gallery_list'] = Gallery.objects.filter(is_standby=False).all()
        context['sample_list'] = Sample.objects.filter(is_standby=False).all()
        context['turnstile_sitekey'] = TURNSTILE_SITEKEY
        # instagramの投稿を取得
        instagram_post_list = InstagramAPIService.get_recent_posts(post_num=9)
        context['instagram_post_list'] = instagram_post_list
        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        token = request.POST.get('cf-turnstile-response')
        remoteip = request.headers.get('CF-Connecting-IP') or \
            request.headers.get('X-Forwarded-For') or \
            request.remote_addr

        validation = validate_turnstile(token, TURNSTILE_SECRET_KEY, remoteip)
        if validation['success']:
            username = request.POST.get('username')
            user_email = request.POST.get('email')
            free_text = request.POST.get('free-text')
            message = "お問い合わせ内容\n"
            message += free_text + "\n\n"
            message += f'お名前: {username} \n'
            message += f'Email: {user_email} \n'
            if not user_email in BLOCK_LIST:
                line_token = env("LINE_TOKEN_ALPHA")
                line_secret = env("LINE_SECRET_ALPHA")
                line_service = LINE_API_Service(account="alpha", token=line_token, secret=line_secret)

                receiver_line_user_id = line_service.get_receiver_user_id()
                try:
                    _ = line_service.send_line_message(
                        user_id=receiver_line_user_id,
                        message=message
                    )
                    context['submitted'] = 'success'
                except MessageConsumptionLimitError:
                    line_token = env("LINE_TOKEN_BETA")
                    line_secret = env("LINE_SECRET_BETA")
                    line_service = LINE_API_Service(account="beta", token=line_token, secret=line_secret)
                    receiver_line_user_id = line_service.get_receiver_user_id()
                    try:
                        _ = line_service.send_line_message(
                            user_id=receiver_line_user_id,
                            message=message
                        )
                        context['submitted'] = 'success'
                    except Exception:
                        context['submitted'] = 'fail'
                except Exception:
                    context['submitted'] = 'fail'

                context['username'] = username
            else:
                context['submitted'] = 'fail'
        else:
            context['submitted'] = 'fail'
        return render(request, self.template_name, context=context)


class OrderView(TemplateView):
    template_name = 'client/order.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_year = datetime.now().year
        context['year'] = current_year
        context['turnstile_sitekey'] = TURNSTILE_SITEKEY
        context['sample_list'] = Sample.objects.filter(is_standby=False).all()
        return context
    
    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        token = request.POST.get('cf-turnstile-response')
        remoteip = request.headers.get('CF-Connecting-IP') or \
            request.headers.get('X-Forwarded-For') or \
            request.remote_addr
       
        validation = validate_turnstile(token, TURNSTILE_SECRET_KEY, remoteip)
        if validation['success']:
            username = request.POST.get('username')
            user_email = request.POST.get('email')
            uniform = request.POST.get('form-uniform')
            socks = request.POST.get('form-socks')
            number = request.POST.get('form-number')
            fabric = request.POST.get('form-fabric')
            neck = request.POST.get('form-neck')
            sleeve = request.POST.get('form-sleeve')
            default = request.POST.get('form-default')
            free_text = request.POST.get('free-text')
            message = '注文が届きました！\n\n'
            message += f'お名前: {username} \n'
            message += f'Email: {user_email} \n'
            message += f'ユニフォーム: {uniform} {socks} \n'
            message += f'枚数: {number} \n'
            message += f'生地: {fabric} \n'
            message += f'襟: {neck} \n'
            message += f'袖: {sleeve} \n'
            message += f'デフォルトデザイン: {default} \n'
            message += f'備考: \n{free_text} \n'
            
            if not user_email in BLOCK_LIST:
                line_token = env("LINE_TOKEN_ALPHA")
                line_secret = env("LINE_SECRET_ALPHA")
                line_service = LINE_API_Service(account="alpha", token=line_token, secret=line_secret)

                receiver_line_user_id = line_service.get_receiver_user_id()
                try:
                    _ = line_service.send_line_message(
                        user_id=receiver_line_user_id,
                        message=message
                    )
                    context['submitted'] = 'success'
                except MessageConsumptionLimitError:
                    line_token = env("LINE_TOKEN_BETA")
                    line_secret = env("LINE_SECRET_BETA")
                    line_service = LINE_API_Service(account="beta", token=line_token, secret=line_secret)
                    receiver_line_user_id = line_service.get_receiver_user_id()
                    try:
                        _ = line_service.send_line_message(
                            user_id=receiver_line_user_id,
                            message=message
                        )
                        context['submitted'] = 'success'
                    except Exception:
                        context['submitted'] = 'fail'
                except Exception:
                    context['submitted'] = 'fail'

                context['username'] = username
            else:
                context['submitted'] = 'fail'
        else:
            context['submitted'] = 'fail'
        return render(request, self.template_name, context=context)


class AboutView(TemplateView):
    template_name = 'client/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_year = datetime.now().year
        context['year'] = current_year
        return context


class FamilyView(TemplateView):
    template_name = 'client/family.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_year = datetime.now().year
        context['year'] = current_year
        context['family_list'] = Family.objects.filter(is_standby=False).all()
        return context


@method_decorator(csrf_exempt, name='dispatch')
class LineWebhookView(TemplateView):
    _ACCOUNT: str
    _LINE_TOKEN: str
    _LINE_SECRET: str

    def setup(self, request, *args, **kwargs):
        """初期化時にトークンとシークレットを設定"""
        super().setup(request, *args, **kwargs)
        self.service = LINE_API_Service(account=self._ACCOUNT, token=self._LINE_TOKEN, secret=self._LINE_SECRET)

    def post(self, request, *args, **kwargs) -> HttpResponse:
        def _handle_service(message: str, user_id: str) -> bool:
            if message == 'list':
                return self.service.get_line_user_list(user_id)
            elif message == 'receiver':
                return self.service.update_receiver_status(user_id)
            elif message.startswith('add '):
                name = message[4:].strip()
                return self.service.add_line_user(user_id, name)
            return False

        if not self.service._check_signature(request):
            return HttpResponse("Invalid signature", status=400)

        body = json.loads(request.body.decode("utf-8"))
        events = body.get("events", [])

        for event in events:
            event_type = event.get("type")  # message / follow / unfollow / postback など
            if event_type != "message":
                continue  # message イベント以外は無視
            message = event.get("message", {})
            user_id = event["source"]["userId"]  # 必ず source から取る

client/templates/client/about.html
{% extends "client/white_page_base.html" %} {% load static %} {% block OGP %}
<head
  prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/ fb# prefix属性: http://ogp.me/ns/ prefix属性#"
>
  <meta property="og:url" content="https://ambicion-jp.com/about" />
  <meta property="og:type" content="article" />
  <meta property="og:title" content="アバウトページ" />
  <meta
    property="og:description"
    content="    スリランカという縫製が盛んな国と旅するサッカー選手。この出会いが、唯一無二のコストパフォーマンスを実現しました。 価格と質。その両方でみなさんを驚かせることができると自負しております。"
  />
  <meta property="og:site_name" content="AMBICIÓNとは？" />
  <meta
    property="og:image"
    content="{% static 'client/images/ryota_bay.jpg' %}"
  />
  <meta name="twitter:card" content="Summary Card" />
  <meta name="twitter:site" content="@Ryota410h" />
  {% endblock OGP %} {% block heading %}
  <h1 class="heading-text">AMBICIÓNとは？</h1>
  {% endblock heading %} {% block bg_picture %}
  <img
    class="background-img container-fluid"
    src="{% static 'client/images/stadium.jpg' %}"
    alt="stadium"
  />
  {% endblock bg_picture %} {% block navigation %}
  <a href="#greeting-nav-target">
    <div class="nav-btn">グリーティング</div>
  </a>
  <a href="#product-nav-target">
    <div class="nav-btn">プロダクト</div>
  </a>
  <a href="#photo-gallery-nav-target">
    <div class="nav-btn">ギャラリー</div>
  </a>
  {% endblock navigation %} {% block contents %}
  <section id="greeting-section" class="before-appear">
    <h1 class="header">代表あいさつ。</h1>
    <hr />
    <div
      id="greeting-first"
      class="before-appear greeting-container row container-fluid"
    >
      <div class="col-lg-6">
        <img
          class="section-img"
          src="{% static 'client/images/ryota_bay.jpg' %}"
          alt="ryota bay"
        />
      </div>
      <div class="col-lg-6">
        <h1 class="text-header">はじめまして！</h1>
        <p class="section-text">
          旅するサッカー選手、林　遼太です。
          <br />
          現在も現役のプロサッカー選手であり、
          <br />
          AMBICIÓNを立ち上げた張本人です。
          <br />
          きっかけは、
          <br />
          僕がスリランカのSEA HAWKS FCに所属したことから。
          <br />
          スリランカという国は、実は衣類産業が盛んで、
          <br />
          高い技術を持った工場が多い国です。
          <br />
          そして偶然出会った１つの工場。
          <br />
          その品質の高さと、働く人々の暖かさに心を動かされました。
          <br />
          <br />
          「こんなに素晴らしいユニフォームたちを、
          <br />
          スリランカのなかだけにとどめておくのは、もったいない！」
          <br />
          この情熱を彼らにぶつけました。
        </p>
      </div>
    </div>
    <div
      id="greeting-second"
      class="before-appear greeting-container row container-fluid"
    >
      <div class="col-lg-6 order-lg-2">
        <img
          class="section-img"
          src="{% static 'client/images/stuff.jpg' %}"
          alt="stuff"
        />
      </div>
      <div class="col-lg-6 order-lg-1">
        <h1 class="text-header">日本、そして世界へ！</h1>
        <p class="section-text">
          写真は工場を運営するスミス夫妻と僕です。
          <br />
          彼らもまた、自分達の製品を世界に届けたいという
          <br />
          熱い志をもっていました。
          <br />
          一致した僕らの志（アンビシオン）を胸に、
          <br />
          AMBICIÓNを立ち上げることを決心しました。
          <br />
          <br />
          「新しいサッカーチームのユニフォームを作りたい。」
          <br />
          「チーム運営をより経済的に、でも質は落としたくない。」
          <br />
          「オリジナルユニフォームで、
          <br />
          所属するサークルの気持ちを一つにしたい。」
          <br />
          さまざまなみなさんの志を、
          <br />
          AMBICIÓNと共に叶えましょう！
          <br />
        </p>
      </div>
    </div>
  </section>
  <section id="product-section" class="before-appear">
    <span id="product-nav-target"></span>
    <hr class="nav-border" />
    <h1 class="header">私たちが作ります。</h1>
    <hr />
    <div class="product-heading">
      <h2 class="text-header">工場の様子、スミスさんの想い。</h2>
      <iframe
        class="youtube-about"
        src="https://www.youtube.com/embed/FSo8q9kxkPE?si=b9muMGGHc1MZY84Y"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        referrerpolicy="strict-origin-when-cross-origin"
        allowfullscreen
      >
      </iframe>
    </div>
    <a href="#product-detail">
      <img
        width="100%"
        height="100%"
        id="product-detail"
        class="allow-img"
        src="{% static 'client/images/design_pieces/allow-black.png' %}"
        alt=""
      />
    </a>
    <div class="product-detail row container-fluid">
      <div class="section-text col-lg-6">
        <h2 class="text-header">プロクオリティ。</h2>
        <p class="section-text">
          現地の工場では、
          <br />
          専門の機械と熟練された技術者たちにより、
          <br />
          プロクオリティのユニフォームを作成しています。
          <br />
          代表自身がプロサッカー選手であり、
          <br />
          本人がその質の高さに驚いたほどです。
          <br />
        </p>
      </div>
      <div class="section-text col-lg-6">
        <h1 class="text-header">圧倒的安さ。</h1>
        <p class="section-text">
          AMBICIÓNでは、
          <br />
          工場と代表の信頼関係のもと、
          <br />
          代理店などは一切通しておりません。
          <br />
          工場から直接みなさんのところまで
          <br />
          ユニフォームをお届けしております。
          <br />
        </p>
      </div>
      <div class="container-fluid">
        <div class="section-text">
          <p class="conclusion">
            <strong>スリランカ</strong>という縫製が盛んな国と<strong
              >旅するサッカー選手。</strong
            >
            <br />
            この出会いが、<strong>唯一無二のコストパフォーマンス</strong>を実現しました。
            <br />
            <strong>価格と質。</strong>
            <br />
            その両方でみなさんを驚かせることができると自負しております。
            <br />
          </p>
        </div>
        <a href="{% url 'client:order' %}">
          <button type="button" class="rounded-0 section-btn btn btn-primary">
            見積もり
          </button>
        </a>
      </div>
      <span id="photo-gallery-nav-target"></span>
    </div>
  </section>
  <section id="photo-gallery-section" class="before-appear">
    <hr class="gallery-border" />
    <h2 class="small-header">
      <i class="fa-solid fa-camera-retro"></i>フォトギャラリー
    </h2>
    <div class="row">
      <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/sea_hawks.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="sea hawks fc"
        />
        <img
          src="{% static 'client/images/gallery/ryota_standing.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="standing ryota"
        />
      </div>
      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/sea_hawks_back.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="uniform back"
        />
        <img
          src="{% static 'client/images/gallery/ryota_kids.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="with kids"
        />
      </div>
      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/ryota_teammate.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="teammate family"
        />
        <img
          src="{% static 'client/images/gallery/ryota_kinoko.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="under the kinoko"
        />
      </div>
      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/ryota_game2.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="game scene"
        />
      </div>
      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/ryota_game1.jpg' %}"
          class="w-100 bottom-center-img shadow-1-strong rounded mb-4"
          alt="game scene"
        />
      </div>
      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/ryota_game3.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="game scene"
        />
      </div>
    </div>
  </section>
  {% endblock contents %}
</head>

client/templates/client/family.html
{% extends 'client/white_page_base.html' %} {% load static %} {% block OGP %}
<head
  prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/ fb# prefix属性: http://ogp.me/ns/ prefix属性#"
>
  <meta property="og:url" content="https://ambicion-jp.com/about" />
  <meta property="og:type" content="article" />
  <meta property="og:title" content="アバウトページ" />
  <meta
    property="og:description"
    content="    スリランカという縫製が盛んな国と旅するサッカー選手。この出会いが、唯一無二のコストパフォーマンスを実現しました。
    価格と質。その両方でみなさんを驚かせることができると自負しております。"
  />
  <meta property="og:site_name" content="AMBICIÓNとは？" />
  <meta
    property="og:image"
    content="{% static 'client/images/ryota_bay.jpg' %}"
  />
  <meta name="twitter:card" content="Summary Card" />
  <meta name="twitter:site" content="@Ryota410h" />
  {% endblock OGP %} {% block heading %}
  <h1 class="heading-text">AMBICIÓNとは？</h1>
  {% endblock %} {% block bg_picture %}
  <img
    class="background-img container-fluid"
    src="{% static 'client/images/stadium.jpg' %}"
    alt="stadium"
  />
  {% endblock %} {% block navigation %}
  <a href="#greeting-nav-target">
    <div class="nav-btn">グリーティング</div>
  </a>
  <a href="#product-nav-target">
    <div class="nav-btn">プロダクト</div>
  </a>
  <a href="#photo-gallery-nav-target">
    <div class="nav-btn">ギャラリー</div>
  </a>
  {% endblock %} {% block contents %}
  <section id="greeting-section" class="before-appear">
    <h1 class="header">代表あいさつ。</h1>
    <hr />
    <div
      id="greeting-first"
      class="before-appear greeting-container row container-fluid"
    >
      <div class="col-lg-6">
        <img
          class="section-img"
          src="{% static 'client/images/ryota_bay.jpg' %}"
          alt="ryota bay"
        />
      </div>
      <div class="col-lg-6">
        <h1 class="text-header">はじめまして！</h1>
        <p class="section-text">
          旅するサッカー選手、林　遼太です。<br />
          現在も現役のプロサッカー選手であり、<br />
          AMBICIÓNを立ち上げた張本人です。<br />
          きっかけは、 <br />僕がスリランカのSEA HAWKS FCに所属したことから。
          <br />
          スリランカという国は、実は衣類産業が盛んで、<br />高い技術を持った工場が多い国です。<br />
          そして偶然出会った１つの工場。<br />その品質の高さと、働く人々の暖かさに心を動かされました。<br /><br />
          「こんなに素晴らしいユニフォームたちを、<br />スリランカのなかだけにとどめておくのは、もったいない！」<br />
          この情熱を彼らにぶつけました。
        </p>
      </div>
    </div>

    <div
      id="greeting-second"
      class="before-appear greeting-container row container-fluid"
    >
      <div class="col-lg-6 order-lg-2">
        <img
          class="section-img"
          src="{% static 'client/images/stuff.jpg' %}"
          alt="stuff"
        />
      </div>

      <div class="col-lg-6 order-lg-1">
        <h1 class="text-header">日本、そして世界へ！</h1>
        <p class="section-text">
          写真は工場を運営するスミス夫妻と僕です。<br />
          彼らもまた、自分達の製品を世界に届けたいという<br />
          熱い志をもっていました。<br />
          一致した僕らの志（アンビシオン）を胸に、
          <br />AMBICIÓNを立ち上げることを決心しました。 <br /><br />
          「新しいサッカーチームのユニフォームを作りたい。」<br />
          「チーム運営をより経済的に、でも質は落としたくない。」<br />
          「オリジナルユニフォームで、<br />所属するサークルの気持ちを一つにしたい。」<br />
          さまざまなみなさんの志を、<br />
          AMBICIÓNと共に叶えましょう！<br />
        </p>
      </div>
    </div>
  </section>

  <section id="product-section" class="before-appear">
    <span id="product-nav-target"></span>
    <hr class="nav-border" />
    <h1 class="header">私たちが作ります。</h1>
    <hr />
    <div class="product-heading">
      <h2 class="text-header">工場の様子、スミスさんの想い。</h2>
      <iframe
        class="youtube-about"
        src="https://www.youtube.com/embed/FSo8q9kxkPE"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
      >
      </iframe>
    </div>
    <a href="#product-detail"
      ><img
        id="product-detail"
        class="allow-img"
        src="{% static 'client/images/design_pieces/allow-black.png' %}"
        alt=""
    /></a>
    <div class="product-detail row container-fluid">
      <div class="section-text col-lg-6">
        <h2 class="text-header">プロクオリティ。</h2>
        <p class="section-text">
          現地の工場では、<br />
          専門の機械と熟練された技術者たちにより、<br />
          プロクオリティのユニフォームを作成しています。<br />
          代表自身がプロサッカー選手であり、<br />本人がその質の高さに驚いたほどです。<br />
        </p>
      </div>
      <div class="section-text col-lg-6">
        <h1 class="text-header">圧倒的安さ。</h1>
        <p class="section-text">
          AMBICIÓNでは、<br />
          工場と代表の信頼関係のもと、 <br />代理店などは一切通しておりません。
          <br />
          工場から直接みなさんのところまで
          <br />ユニフォームをお届けしております。<br />
        </p>
      </div>

      <div class="container-fluid">
        <div class="section-text">
          <p class="conclusion">
            <strong>スリランカ</strong>という縫製が盛んな国と<strong
              >旅するサッカー選手。</strong
            ><br />
            この出会いが、<strong>唯一無二のコストパフォーマンス</strong>を実現しました。<br />
            <strong>価格と質。</strong
            ><br />その両方でみなさんを驚かせることができると自負しております。<br />
          </p>
        </div>
        <a href="{% url 'client:order' %}">
          <button type="button" class="rounded-0 section-btn btn btn-primary">
            見積もり
          </button>
        </a>
      </div>
      <span id="photo-gallery-nav-target"></span>
    </div>
  </section>

  <section id="photo-gallery-section" class="before-appear">
    <hr class="gallery-border" />

    <h2 class="small-header">
      <i class="fa-solid fa-camera-retro"></i>フォトギャラリー
    </h2>
    <div class="row">
      <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/sea_hawks.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="sea hawks fc"
        />

        <img
          src="{% static 'client/images/gallery/ryota_standing.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="standing ryota"
        />
      </div>

      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/sea_hawks_back.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="uniform back"
        />

        <img
          src="{% static 'client/images/gallery/ryota_kids.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="with kids"
        />
      </div>

      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/ryota_teammate.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="teammate family"
        />

        <img
          src="{% static 'client/images/gallery/ryota_kinoko.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="under the kinoko"
        />
      </div>

      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/ryota_game2.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="game scene"
        />
      </div>

      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/ryota_game1.jpg' %}"
          class="bottom-center-img w-100 shadow-1-strong rounded mb-4"
          alt="game scene"
        />
      </div>

      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="{% static 'client/images/gallery/ryota_game3.jpg' %}"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="game scene"
        />
      </div>
    </div>
  </section>

  {% endblock %}
</head>